name: not_so_tic_tac_toe_game
description: A simple Tic Tac Toe game
version: 1.0.0
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  file_saver: 0.3.1
  image: ^4.0.0
  share_plus: ^12.0.0
  cloud_firestore: '>=5.5.0'
  firebase_auth: '>=5.3.3'
  flutter_riverpod: ^3.0.0
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^4.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/fonts/
  fonts:
    - family: NotoSans
      fonts:
        - asset: assets/fonts/NotoSans-Regular.ttf
        - asset: assets/fonts/NotoSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/NotoSans-Italic.ttf
          style: italic
        - asset: assets/fonts/NotoSans-BoldItalic.ttf
          weight: 700
          style: italic
